server:  port: 8765
eureka:  client:    service-url:      defaultZone: http://localhost:8761/eureka  instance:    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}spring:
  application:    name: hr-apigateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true          lower-case-service-id: true
      routes:
      - id: hr-worker
        uri: lb://hr-worker
        predicates:
        - "Path=/hr-worker/**"
      - id: hr-payroll
        uri: lb://hr-payroll
        predicates:
        - "Path=/hr-payroll/**"